name: Deploy to SiteGround via FTP

on:
  push:
    branches:
      - main  # Set to your default branch, e.g., master or main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Build React App
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: chris@kellym107.sg-host.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: client/build/
          dangerous-clean-slate: true
          server-dir: kellym107.sg-host.com/public_html/
          port: 21
          git-ftp-args: --insecure  # Use this if your FTP server does not support FTPS
          # For more secure FTP (like SFTP or FTPS), see the action's documentation for additional configuration

